// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.genmymodel.shoppingcart.domain;

import com.genmymodel.shoppingcart.domain.Order_;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Order__Roo_Configurable {
    
    declare @type: Order_: @Configurable;
    
}
